name = "Example Modpack"
author = "Team Atelier"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9049333cce0d17608195c329938f74a93ec1653c9deb4a473aa0af071b3b2273"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
