name = "Example Modpack"
author = "Team Atelier"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6bbd629e111c802c083d22d11888d441cb6ecdd8c710e87ece8d68759fc4aa7d"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
