name = "Example Modpack"
author = "Team Atelier"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1233e4def1c0c69d0f03624ba0b479ac864674714ee28c7baafe905f3b662e4"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
